# PSCloud Exporter Configuration
# Token can be left empty here and set via PSCLOUD_TOKEN environment variable
token: ""  # Can be left empty and set via PSCLOUD_TOKEN environment variable
serviceId: ""  # Service ID for VPC and VPS API requests (optional)
baseUrl: "https://console.ps.kz"  # Base URL for PS.KZ API (optional)

# Web server configuration
web:
  listenAddress: ":9116"
  metricsPrefix: "pskz"
  telemetryPath: "/metrics" 