# PSCloud Exporter Configuration
token: "your_token"  # Access token for PS.KZ application
serviceId: "12345"   # Service ID for VPC and VPS API requests (optional)

# Web server configuration
web:
  listenAddress: ":9116"
  metricsPrefix: "pskz"
  telemetryPath: "/metrics" 