apiVersion: v1
kind: ConfigMap
metadata:
  name: pscloud-exporter-config
  namespace: monitoring
data:
  config.yaml: |
    # PSCloud Exporter Configuration
    baseUrl: "https://api.ps.kz/v1"
    useHttp: false

    # Web server configuration
    web:
      listenAddress: ":9116"
      metricsPrefix: "pskz"
      telemetryPath: "/metrics" 