apiVersion: v1
kind: Service
metadata:
  name: pscloud-exporter
  namespace: monitoring
  labels:
    app: pscloud-exporter
spec:
  ports:
  - port: 9116
    targetPort: metrics
    protocol: TCP
    name: metrics
  selector:
    app: pscloud-exporter 